### ISSUE TITLE
Broke my world

### ISSUE THREAD

**Issue by StingerDragon** [SFort/MC-invisframes#10]
Was building and decided to download this mod to give it a more “realistic” feeling. Got it in the folder, loaded up the game and save file… and my whole world is gone. I’m basically in the void, and I can’t get my world back, even when deleting backups.

**Comment by SFort** [comment]
upload the game log and the broken world.
does it happen consistently or that world specificly?

**Comment by StingerDragon** [comment]
I only have one world, but the world only “voided” after I installed it; it was fine prior. I can try a brand new world with it installed and see if that works

**Comment by SFort** [comment]
without a log / game world i have nothing to work, i don't even know what mc version you're on or what invisframes version you're using.
there's a chance it'll be pretty obvious what happened by just looking at the logs.
they're in `.minecraft/logs` and should be marked with dates so you still should have the original log from when the world first broke. (and new logs in case the issue is reproducable)

i also did test all of the released versions and none came close to having this sort of issue, so i'm assuminng it's a mod conflict, which is something that you'll have a much easier time finding out. (by removing/adding other mods / invisframes and seeing if the issue persist)

**Comment by StingerDragon** [comment]
[2023-02-24-6.log.gz](https://github.com/SFort/MC-invisframes/files/10831554/2023-02-24-6.log.gz)
[2023-02-24-5.log.gz](https://github.com/SFort/MC-invisframes/files/10831555/2023-02-24-5.log.gz)

Attached the two before and after I installed the mods; the first one was with a (Forge?) version 2.0.1, then i tried 2.0.0 but it said it was fabric and couldn't be loaded. 

**just tried it now with a new world - apparently it was just that world that was messed up.

**Comment by SFort** [comment]
`Saving chunks for level 'ServerLevel[plz just fucken work]'`
heh

generally the mod is fabric, the 1.16 forge version exists mostly because someone asked for it and i happened to have time.

there really really really shouldn't be a way invisframes caused word corruption especially on that version.

looks like you just got very unlucky and the world just happened to get corrupt
if you still have the world that got corrupt you could get it's seed and regen it. if the same seed crashes it's probably a mod that adds corrupting worldgen. almost certanly not invis frames though.
