### ISSUE TITLE
Armorstand are always visible (even with Invisible:1b NBT tag)

### ISSUE THREAD

**Issue by SozoKa** [SFort/MC-invisframes#11]
![Example screenshot](https://user-images.githubusercontent.com/70240607/227340494-0433810b-6007-4ae2-86d2-1274ab7c02e6.png)

**Comment by SFort** [comment]
since 2.2.0 armor stands can be set invis the same as item frames.

to stop them from being visable go to `.minecraft/config/InvisFrames.conf`
change the line above `Armor Stand has item check` to `none`

if you also want to prevent them toggling visability in survival (via shift-punching)
set the line above `Enable invis armor stands` to `false`

i probably should have had these as the defaults...
i'll change the defaults whenever i get around to updating the config format to ini

sorry for the annoyance, neat graphic though

**Comment by SozoKa** [comment]
Oh, I tried to do a shift-punch and it didn't change anything... :') And as I didn't see any custom settings in the modmenu I thought it was a bug... Thank you !

And thanks for the compliment, I worked hard on it ;)

**Comment by SFort** [comment]
changed config to ini in 2.2.1 (has some advantages and looks better in text editors)
and defaulted invis armor stands to off (if you already changed it, it'll figure it out no need todo it again)

and yeee i really need to get around to modmenu stuff, just very indecicive about how to handle it.

**Comment by SozoKa** [comment]
That is and would be awesome :))
